#!/bin/sh

# pack.sh
# Pack every lua source into a single file for distribution.


PACKED_DIR=$(realpath $(dirname $0))/.temp
mkdir -p $PACKED_DIR
PACKED_FILE="$PACKED_DIR/packed"
DELIM=--------------------------------------------------

if [ -e $PACKED_FILE ]; then
	rm $PACKED_FILE
fi
echo "------- This file has been autogenerated! --------" > $PACKED_FILE

cd "$(dirname $0)/src"
for f in $(find * -type f -iregex '.*\.lua' | tr "\n" " "); do
	echo "$DELIM" >> $PACKED_FILE
	echo "/atref/$(dirname $f)" >> $PACKED_FILE
	echo $(basename $f) >> $PACKED_FILE
	echo $DELIM >> $PACKED_FILE
	cat $f >> $PACKED_FILE
done