#!/bin/sh

# pack.sh
# Pack every lua source into a single file for distribution.

mkdir -p .temp
PACKED_FILE=$(realpath ".temp/packed")

DELIM="--------------------------------------------------"
HEADER="------- This file has been autogenerated! --------"

echo $HEADER > $PACKED_FILE

cd "$(dirname $0)/src"
for f in $(find * -type f -iregex '.*\.lua' | tr "\n" " "); do
	echo "$DELIM" >> $PACKED_FILE
	echo "/atref/$(dirname $f)" >> $PACKED_FILE
	echo $(basename $f) >> $PACKED_FILE
	echo $DELIM >> $PACKED_FILE
	cat $f >> $PACKED_FILE
done