#!/bin/sh

# pack.sh
# Pack every lua source into a single file for distribution.

PACKED="$(realpath $(dirname $0)/.packed)"
DELIM=--------------------------------------------------

if [ -e $PACKED ]; then
	rm $PACKED
fi
echo "------- This file has been autogenerated! --------" > $PACKED

cd "$(dirname $0)/src"
for f in $(find * -type f -iregex '.*\.lua' | tr "\n" " "); do
	echo "$DELIM" >> $PACKED
	echo "/atref/$(dirname $f)" >> $PACKED
	echo $(basename $f) >> $PACKED
	echo $DELIM >> $PACKED
	cat $f >> $PACKED
done