name: Release

on: 
  push:
    tags: [ '*' ]

permissions:
  contents: write

jobs:
  release_on_tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: pack
        run: ./pack.sh
      - name: release
        uses: nicovince/manage-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          files: .temp/packed
          tag: ${{ github.ref_name }}
